# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# support for **
shopt -s globstar
shopt -s cdspell
shopt -s cmdhist
shopt -s dirspell

# set environment variables
export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export LC_TYPES=en_US.UTF-8
export LANG=en_US.UTF-8
export POWERLINE_BASH_CONTINUATION=1
export POWERLINE_BASH_SELECT=1
export POWERLINE_INSTALL_PATH=`pip show powerline-status | grep Location | awk '{print $2}'`/powerline
export GOROOT=~/go
export GOPATH=$HOME/env/golang
export PATH=$PATH:$HOME/bin:$GOPATH/bin

# aliases
alias s='ssh $*'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ls='ls --color=auto $*'
alias ll='ls -l --color=auto $*'
alias grep='grep --color=auto $*'
alias fgrep='fgrep --color=auto $*'
alias egrep='egrep --color=auto $*'
alias du1='du --max-depth=1 $*'
alias tree1='tree -L 1 $*'
# alias tmux='tmux -2 $*'

if [ "$(uname)" == "Linux" ]; then
    # Linux specific config.
    if ! shopt -oq posix; then
      if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
      elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
      fi
    fi
    
    if [ -f `which powerline-daemon` ]; then
        flock -xn /tmp/powerline-daemon.lock powerline-daemon -q
        . ${POWERLINE_INSTALL_PATH}/bindings/bash/powerline.sh
    fi

elif [ "$(uname)" == "Darwin" ]; then
    # OS X specific config.
    HOMEBREW_PREFIX=$(brew --prefix)
    export PATH=$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH
    export MANPATH=$HOMEBREW_PREFIX/opt/coreutils/libexec/gnuman:$MANPATH

    if [ -f $HOMEBREW_PREFIX/etc/bash_completion  ]; then
        . $HOMEBREW_PREFIX/etc/bash_completion
    fi

    if [ -f `which powerline-daemon` ]; then
        . ${POWERLINE_INSTALL_PATH}/bindings/bash/powerline.sh
    fi
fi
